import type { Product } from "@/types";

// Sample products for display when backend is loading or empty
export const SAMPLE_PRODUCTS: Product[] = [
  // --- PREMIUM ---
  {
    id: "p1",
    name: "Anya Embroidered Silk Kurti",
    description:
      "Exquisitely handcrafted with pure silk fabric and intricate gold zari embroidery. Perfect for festive occasions and special gatherings. Features a mandarin collar, 3/4 sleeves, and a straight silhouette with side slits.",
    price: 2850,
    originalPrice: 3500,
    tier: "premium",
    category: "kurti",
    imageUrl: "/assets/generated/product-premium-kurti-1.dim_600x800.jpg",
    images: [
      "/assets/generated/product-premium-kurti-1.dim_600x800.jpg",
      "/assets/generated/product-premium-dupatta-1.dim_600x800.jpg",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Teal", "Ivory"],
    inStock: true,
    stockCount: 12,
    tags: ["silk", "embroidered", "festive", "kurti"],
    createdAt: Date.now() - 86400000 * 5,
    updatedAt: Date.now(),
  },
  {
    id: "p2",
    name: "Serene Silk Palazzo Set",
    description:
      "A luxurious co-ord set crafted from premium crepe silk. Features subtle floral block print, wide-leg palazzo pants, and a flowy A-line kurta. Comes with a matching dupatta.",
    price: 3990,
    originalPrice: 4800,
    tier: "premium",
    category: "set",
    imageUrl: "/assets/generated/product-average-kurti-1.dim_600x800.jpg",
    images: ["/assets/generated/product-average-kurti-1.dim_600x800.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Deep Navy", "Burgundy"],
    inStock: true,
    stockCount: 7,
    tags: ["silk", "palazzo", "set", "festive"],
    createdAt: Date.now() - 86400000 * 3,
    updatedAt: Date.now(),
  },
  {
    id: "p3",
    name: "Zara Palazzo Kurti Set",
    description:
      "Designer kurti and palazzo set with hand block print on pure cotton fabric. A timeless classic updated with contemporary proportions.",
    price: 3100,
    tier: "premium",
    category: "set",
    imageUrl: "/assets/generated/product-premium-dupatta-1.dim_600x800.jpg",
    images: ["/assets/generated/product-premium-dupatta-1.dim_600x800.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Teal", "Rust", "Indigo"],
    inStock: true,
    stockCount: 5,
    tags: ["block print", "palazzo", "set"],
    createdAt: Date.now() - 86400000 * 7,
    updatedAt: Date.now(),
  },
  {
    id: "p4",
    name: "Kyra Embellished Kurti",
    description:
      "Opulent georgette kurti adorned with mirror work and thread embroidery. Straight-cut silhouette with scalloped hemline.",
    price: 2600,
    originalPrice: 3200,
    tier: "premium",
    category: "kurti",
    imageUrl: "/assets/generated/product-premium-kurti-1.dim_600x800.jpg",
    images: ["/assets/generated/product-premium-kurti-1.dim_600x800.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Navy", "Maroon"],
    inStock: false,
    stockCount: 0,
    tags: ["georgette", "embellished", "mirror work"],
    createdAt: Date.now() - 86400000 * 10,
    updatedAt: Date.now(),
  },

  // --- AVERAGE ---
  {
    id: "a1",
    name: "Diya Cotton Printed Kurti",
    description:
      "Everyday breezy kurti in premium cotton with contemporary floral print. Features a V-neck, 3/4 sleeves, and comfortable A-line cut. Perfect for office or casual outings.",
    price: 1450,
    originalPrice: 1800,
    tier: "average",
    category: "kurti",
    imageUrl: "/assets/generated/product-average-kurti-1.dim_600x800.jpg",
    images: [
      "/assets/generated/product-average-kurti-1.dim_600x800.jpg",
      "/assets/generated/product-average-pants-1.dim_600x800.jpg",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Navy Blue", "Coral", "Sage Green"],
    inStock: true,
    stockCount: 32,
    tags: ["cotton", "printed", "everyday"],
    createdAt: Date.now() - 86400000 * 2,
    updatedAt: Date.now(),
  },
  {
    id: "a2",
    name: "Mira Linen Palazzo Pants",
    description:
      "Flowy linen palazzo pants with an elasticated waistband. Lightweight, breathable, and versatile — pairs beautifully with any kurti.",
    price: 1200,
    tier: "average",
    category: "pants",
    imageUrl: "/assets/generated/product-average-pants-1.dim_600x800.jpg",
    images: ["/assets/generated/product-average-pants-1.dim_600x800.jpg"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Beige", "Navy"],
    inStock: true,
    stockCount: 45,
    tags: ["linen", "palazzo", "pants"],
    createdAt: Date.now() - 86400000 * 6,
    updatedAt: Date.now(),
  },
  {
    id: "a3",
    name: "Leela Printed Kurti Set",
    description:
      "Versatile kurti + dupatta set in Jaipuri block print. The straight-cut kurti is paired with a matching printed dupatta for a complete look.",
    price: 1600,
    originalPrice: 1950,
    tier: "average",
    category: "set",
    imageUrl: "/assets/generated/product-average-kurti-1.dim_600x800.jpg",
    images: ["/assets/generated/product-average-kurti-1.dim_600x800.jpg"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Yellow", "Pink"],
    inStock: true,
    stockCount: 18,
    tags: ["block print", "set", "dupatta"],
    createdAt: Date.now() - 86400000 * 8,
    updatedAt: Date.now(),
  },
  {
    id: "a4",
    name: "Roohi Anarkali Set",
    description:
      "Elegant anarkali kurti with flared skirt silhouette and contrast border work. Perfect for festive and semi-formal occasions.",
    price: 1750,
    tier: "average",
    category: "set",
    imageUrl: "/assets/generated/product-average-pants-1.dim_600x800.jpg",
    images: ["/assets/generated/product-average-pants-1.dim_600x800.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Teal", "Wine"],
    inStock: true,
    stockCount: 9,
    tags: ["anarkali", "set", "festive"],
    createdAt: Date.now() - 86400000 * 4,
    updatedAt: Date.now(),
  },

  // --- BASIC ---
  {
    id: "b1",
    name: "Sia Basic Cotton Kurti",
    description:
      "Comfortable everyday cotton kurti in a simple, fuss-free design. Available in a range of solid colours to mix and match with your wardrobe staples.",
    price: 890,
    originalPrice: 1100,
    tier: "basic",
    category: "kurti",
    imageUrl: "/assets/generated/product-basic-kurti-1.dim_600x800.jpg",
    images: [
      "/assets/generated/product-basic-kurti-1.dim_600x800.jpg",
      "/assets/generated/product-basic-top-1.dim_600x800.jpg",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["White", "Light Blue", "Olive", "Dusty Pink"],
    inStock: true,
    stockCount: 60,
    tags: ["cotton", "basic", "everyday", "solid"],
    createdAt: Date.now() - 86400000 * 1,
    updatedAt: Date.now(),
  },
  {
    id: "b2",
    name: "Ritu Straight Pants",
    description:
      "Casual straight-fit pants in soft cotton fabric. High-rise waistband with a relaxed leg — the ultimate everyday essential.",
    price: 750,
    tier: "basic",
    category: "pants",
    imageUrl: "/assets/generated/product-basic-top-1.dim_600x800.jpg",
    images: ["/assets/generated/product-basic-top-1.dim_600x800.jpg"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Black", "Navy", "Beige"],
    inStock: true,
    stockCount: 80,
    tags: ["cotton", "pants", "basic"],
    createdAt: Date.now() - 86400000 * 9,
    updatedAt: Date.now(),
  },
  {
    id: "b3",
    name: "Noor Casual Top",
    description:
      "A simple, breathable cotton-blend top that pairs well with pants or jeans. No fuss, just comfort.",
    price: 950,
    tier: "basic",
    category: "top",
    imageUrl: "/assets/generated/product-basic-top-1.dim_600x800.jpg",
    images: ["/assets/generated/product-basic-top-1.dim_600x800.jpg"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["White", "Ivory", "Sky Blue"],
    inStock: true,
    stockCount: 40,
    tags: ["top", "basic", "cotton"],
    createdAt: Date.now() - 86400000 * 11,
    updatedAt: Date.now(),
  },
  {
    id: "b4",
    name: "Veda Straight Kurti",
    description:
      "A classic straight kurti in soft cotton with simple pintuck detailing. The wardrobe essential you'll reach for every day.",
    price: 900,
    originalPrice: 1050,
    tier: "basic",
    category: "kurti",
    imageUrl: "/assets/generated/product-basic-kurti-1.dim_600x800.jpg",
    images: ["/assets/generated/product-basic-kurti-1.dim_600x800.jpg"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: ["Camel", "White", "Lavender"],
    inStock: false,
    stockCount: 0,
    tags: ["straight", "kurti", "cotton", "basic"],
    createdAt: Date.now() - 86400000 * 14,
    updatedAt: Date.now(),
  },
];

export function getProductsByTier(tier: string) {
  return SAMPLE_PRODUCTS.filter((p) => p.tier === tier);
}

export function getProductById(id: string) {
  return SAMPLE_PRODUCTS.find((p) => p.id === id) ?? null;
}
