/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProductId = IDL.Nat;
export const AddToCartRequest = IDL.Record({
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const UserId = IDL.Principal;
export const CartItemId = IDL.Nat;
export const ProductTier = IDL.Variant({
  'premium' : IDL.Null,
  'average' : IDL.Null,
  'basic' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const CartItem = IDL.Record({
  'id' : CartItemId,
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'productName' : IDL.Text,
  'productTier' : ProductTier,
  'imageUrl' : IDL.Opt(IDL.Text),
  'addedAt' : Timestamp,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Cart = IDL.Record({
  'tax' : IDL.Nat,
  'total' : IDL.Nat,
  'userId' : UserId,
  'items' : IDL.Vec(CartItem),
  'subtotal' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderItemRequest = IDL.Record({
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'quantity' : IDL.Nat,
});
export const CreateOrderRequest = IDL.Record({
  'items' : IDL.Vec(OrderItemRequest),
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'color' : IDL.Opt(IDL.Text),
  'size' : IDL.Opt(IDL.Text),
  'productId' : ProductId,
  'productName' : IDL.Text,
  'productTier' : ProductTier,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'tax' : IDL.Nat,
  'status' : OrderStatus,
  'total' : IDL.Nat,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'stripePaymentIntentId' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(OrderItem),
  'orderNumber' : IDL.Text,
  'subtotal' : IDL.Nat,
});
export const ProductSize = IDL.Text;
export const ProductColor = IDL.Text;
export const CreateProductRequest = IDL.Record({
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'tier' : ProductTier,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(ProductSize),
  'stock' : IDL.Nat,
  'colors' : IDL.Vec(ProductColor),
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'imageUrls' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'tier' : ProductTier,
  'description' : IDL.Text,
  'sizes' : IDL.Vec(ProductSize),
  'updatedAt' : Timestamp,
  'stock' : IDL.Nat,
  'colors' : IDL.Vec(ProductColor),
  'price' : IDL.Nat,
});
export const UpdateProductRequest = IDL.Record({
  'imageUrls' : IDL.Opt(IDL.Vec(IDL.Text)),
  'name' : IDL.Opt(IDL.Text),
  'tier' : IDL.Opt(ProductTier),
  'description' : IDL.Opt(IDL.Text),
  'sizes' : IDL.Opt(IDL.Vec(ProductSize)),
  'stock' : IDL.Opt(IDL.Nat),
  'colors' : IDL.Opt(IDL.Vec(ProductColor)),
  'price' : IDL.Opt(IDL.Nat),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addToCart' : IDL.Func([AddToCartRequest], [IDL.Opt(Cart)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearMyCart' : IDL.Func([], [], []),
  'createOrder' : IDL.Func([CreateOrderRequest], [IDL.Opt(Order)], []),
  'createProduct' : IDL.Func([CreateProductRequest], [Product], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyCart' : IDL.Func([], [Cart], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'listProductsByTier' : IDL.Func([ProductTier], [IDL.Vec(Product)], ['query']),
  'removeFromCart' : IDL.Func([CartItemId], [Cart], []),
  'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'setOrderPaymentIntent' : IDL.Func([OrderId, IDL.Text], [IDL.Opt(Order)], []),
  'updateCartItemQuantity' : IDL.Func(
      [CartItemId, IDL.Nat],
      [IDL.Opt(Cart)],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Opt(Order)], []),
  'updateProduct' : IDL.Func(
      [ProductId, UpdateProductRequest],
      [IDL.Opt(Product)],
      [],
    ),
  'updateStock' : IDL.Func([ProductId, IDL.Nat], [IDL.Opt(Product)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProductId = IDL.Nat;
  const AddToCartRequest = IDL.Record({
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const UserId = IDL.Principal;
  const CartItemId = IDL.Nat;
  const ProductTier = IDL.Variant({
    'premium' : IDL.Null,
    'average' : IDL.Null,
    'basic' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const CartItem = IDL.Record({
    'id' : CartItemId,
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'productName' : IDL.Text,
    'productTier' : ProductTier,
    'imageUrl' : IDL.Opt(IDL.Text),
    'addedAt' : Timestamp,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Cart = IDL.Record({
    'tax' : IDL.Nat,
    'total' : IDL.Nat,
    'userId' : UserId,
    'items' : IDL.Vec(CartItem),
    'subtotal' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderItemRequest = IDL.Record({
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'quantity' : IDL.Nat,
  });
  const CreateOrderRequest = IDL.Record({
    'items' : IDL.Vec(OrderItemRequest),
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'color' : IDL.Opt(IDL.Text),
    'size' : IDL.Opt(IDL.Text),
    'productId' : ProductId,
    'productName' : IDL.Text,
    'productTier' : ProductTier,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'tax' : IDL.Nat,
    'status' : OrderStatus,
    'total' : IDL.Nat,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'stripePaymentIntentId' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(OrderItem),
    'orderNumber' : IDL.Text,
    'subtotal' : IDL.Nat,
  });
  const ProductSize = IDL.Text;
  const ProductColor = IDL.Text;
  const CreateProductRequest = IDL.Record({
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'tier' : ProductTier,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(ProductSize),
    'stock' : IDL.Nat,
    'colors' : IDL.Vec(ProductColor),
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'imageUrls' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'tier' : ProductTier,
    'description' : IDL.Text,
    'sizes' : IDL.Vec(ProductSize),
    'updatedAt' : Timestamp,
    'stock' : IDL.Nat,
    'colors' : IDL.Vec(ProductColor),
    'price' : IDL.Nat,
  });
  const UpdateProductRequest = IDL.Record({
    'imageUrls' : IDL.Opt(IDL.Vec(IDL.Text)),
    'name' : IDL.Opt(IDL.Text),
    'tier' : IDL.Opt(ProductTier),
    'description' : IDL.Opt(IDL.Text),
    'sizes' : IDL.Opt(IDL.Vec(ProductSize)),
    'stock' : IDL.Opt(IDL.Nat),
    'colors' : IDL.Opt(IDL.Vec(ProductColor)),
    'price' : IDL.Opt(IDL.Nat),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addToCart' : IDL.Func([AddToCartRequest], [IDL.Opt(Cart)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearMyCart' : IDL.Func([], [], []),
    'createOrder' : IDL.Func([CreateOrderRequest], [IDL.Opt(Order)], []),
    'createProduct' : IDL.Func([CreateProductRequest], [Product], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyCart' : IDL.Func([], [Cart], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listOrdersByStatus' : IDL.Func([OrderStatus], [IDL.Vec(Order)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'listProductsByTier' : IDL.Func(
        [ProductTier],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'removeFromCart' : IDL.Func([CartItemId], [Cart], []),
    'searchProducts' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'setOrderPaymentIntent' : IDL.Func(
        [OrderId, IDL.Text],
        [IDL.Opt(Order)],
        [],
      ),
    'updateCartItemQuantity' : IDL.Func(
        [CartItemId, IDL.Nat],
        [IDL.Opt(Cart)],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
    'updateProduct' : IDL.Func(
        [ProductId, UpdateProductRequest],
        [IDL.Opt(Product)],
        [],
      ),
    'updateStock' : IDL.Func([ProductId, IDL.Nat], [IDL.Opt(Product)], []),
  });
};

export const init = ({ IDL }) => { return []; };