/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddToCartRequest {
  'color' : [] | [string],
  'size' : [] | [string],
  'productId' : ProductId,
  'quantity' : bigint,
}
export interface Cart {
  'tax' : bigint,
  'total' : bigint,
  'userId' : UserId,
  'items' : Array<CartItem>,
  'subtotal' : bigint,
}
export interface CartItem {
  'id' : CartItemId,
  'color' : [] | [string],
  'size' : [] | [string],
  'productId' : ProductId,
  'productName' : string,
  'productTier' : ProductTier,
  'imageUrl' : [] | [string],
  'addedAt' : Timestamp,
  'quantity' : bigint,
  'price' : bigint,
}
export type CartItemId = bigint;
export interface CreateOrderRequest { 'items' : Array<OrderItemRequest> }
export interface CreateProductRequest {
  'imageUrls' : Array<string>,
  'name' : string,
  'tier' : ProductTier,
  'description' : string,
  'sizes' : Array<ProductSize>,
  'stock' : bigint,
  'colors' : Array<ProductColor>,
  'price' : bigint,
}
export interface Order {
  'id' : OrderId,
  'tax' : bigint,
  'status' : OrderStatus,
  'total' : bigint,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'stripePaymentIntentId' : [] | [string],
  'items' : Array<OrderItem>,
  'orderNumber' : string,
  'subtotal' : bigint,
}
export type OrderId = bigint;
export interface OrderItem {
  'color' : [] | [string],
  'size' : [] | [string],
  'productId' : ProductId,
  'productName' : string,
  'productTier' : ProductTier,
  'quantity' : bigint,
  'price' : bigint,
}
export interface OrderItemRequest {
  'color' : [] | [string],
  'size' : [] | [string],
  'productId' : ProductId,
  'quantity' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'paid' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export interface Product {
  'id' : ProductId,
  'imageUrls' : Array<string>,
  'name' : string,
  'createdAt' : Timestamp,
  'tier' : ProductTier,
  'description' : string,
  'sizes' : Array<ProductSize>,
  'updatedAt' : Timestamp,
  'stock' : bigint,
  'colors' : Array<ProductColor>,
  'price' : bigint,
}
export type ProductColor = string;
export type ProductId = bigint;
export type ProductSize = string;
export type ProductTier = { 'premium' : null } |
  { 'average' : null } |
  { 'basic' : null };
export type Timestamp = bigint;
export interface UpdateProductRequest {
  'imageUrls' : [] | [Array<string>],
  'name' : [] | [string],
  'tier' : [] | [ProductTier],
  'description' : [] | [string],
  'sizes' : [] | [Array<ProductSize>],
  'stock' : [] | [bigint],
  'colors' : [] | [Array<ProductColor>],
  'price' : [] | [bigint],
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addToCart' : ActorMethod<[AddToCartRequest], [] | [Cart]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearMyCart' : ActorMethod<[], undefined>,
  'createOrder' : ActorMethod<[CreateOrderRequest], [] | [Order]>,
  'createProduct' : ActorMethod<[CreateProductRequest], Product>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyCart' : ActorMethod<[], Cart>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getOrder' : ActorMethod<[OrderId], [] | [Order]>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllOrders' : ActorMethod<[], Array<Order>>,
  'listOrdersByStatus' : ActorMethod<[OrderStatus], Array<Order>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'listProductsByTier' : ActorMethod<[ProductTier], Array<Product>>,
  'removeFromCart' : ActorMethod<[CartItemId], Cart>,
  'searchProducts' : ActorMethod<[string], Array<Product>>,
  'setOrderPaymentIntent' : ActorMethod<[OrderId, string], [] | [Order]>,
  'updateCartItemQuantity' : ActorMethod<[CartItemId, bigint], [] | [Cart]>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
  'updateProduct' : ActorMethod<
    [ProductId, UpdateProductRequest],
    [] | [Product]
  >,
  'updateStock' : ActorMethod<[ProductId, bigint], [] | [Product]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];