/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type ProductColor = string;
export interface Product {
    id: ProductId;
    imageUrls: Array<string>;
    name: string;
    createdAt: Timestamp;
    tier: ProductTier;
    description: string;
    sizes: Array<ProductSize>;
    updatedAt: Timestamp;
    stock: bigint;
    colors: Array<ProductColor>;
    price: bigint;
}
export type Timestamp = bigint;
export interface OrderItem {
    color?: string;
    size?: string;
    productId: ProductId;
    productName: string;
    productTier: ProductTier;
    quantity: bigint;
    price: bigint;
}
export interface Order {
    id: OrderId;
    tax: bigint;
    status: OrderStatus;
    total: bigint;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    stripePaymentIntentId?: string;
    items: Array<OrderItem>;
    orderNumber: string;
    subtotal: bigint;
}
export interface OrderItemRequest {
    color?: string;
    size?: string;
    productId: ProductId;
    quantity: bigint;
}
export type UserId = Principal;
export type ProductSize = string;
export interface CreateProductRequest {
    imageUrls: Array<string>;
    name: string;
    tier: ProductTier;
    description: string;
    sizes: Array<ProductSize>;
    stock: bigint;
    colors: Array<ProductColor>;
    price: bigint;
}
export interface AddToCartRequest {
    color?: string;
    size?: string;
    productId: ProductId;
    quantity: bigint;
}
export interface Cart {
    tax: bigint;
    total: bigint;
    userId: UserId;
    items: Array<CartItem>;
    subtotal: bigint;
}
export type ProductId = bigint;
export interface CreateOrderRequest {
    items: Array<OrderItemRequest>;
}
export type CartItemId = bigint;
export interface CartItem {
    id: CartItemId;
    color?: string;
    size?: string;
    productId: ProductId;
    productName: string;
    productTier: ProductTier;
    imageUrl?: string;
    addedAt: Timestamp;
    quantity: bigint;
    price: bigint;
}
export type OrderId = bigint;
export interface UpdateProductRequest {
    imageUrls?: Array<string>;
    name?: string;
    tier?: ProductTier;
    description?: string;
    sizes?: Array<ProductSize>;
    stock?: bigint;
    colors?: Array<ProductColor>;
    price?: bigint;
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    paid = "paid",
    completed = "completed",
    processing = "processing"
}
export enum ProductTier {
    premium = "premium",
    average = "average",
    basic = "basic"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addToCart(req: AddToCartRequest): Promise<Cart | null>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearMyCart(): Promise<void>;
    createOrder(req: CreateOrderRequest): Promise<Order | null>;
    createProduct(req: CreateProductRequest): Promise<Product>;
    deleteProduct(id: ProductId): Promise<boolean>;
    getCallerUserRole(): Promise<UserRole>;
    getMyCart(): Promise<Cart>;
    getMyOrders(): Promise<Array<Order>>;
    getOrder(id: OrderId): Promise<Order | null>;
    getProduct(id: ProductId): Promise<Product | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllOrders(): Promise<Array<Order>>;
    listOrdersByStatus(status: OrderStatus): Promise<Array<Order>>;
    listProducts(): Promise<Array<Product>>;
    listProductsByTier(tier: ProductTier): Promise<Array<Product>>;
    removeFromCart(cartItemId: CartItemId): Promise<Cart>;
    searchProducts(searchTerm: string): Promise<Array<Product>>;
    setOrderPaymentIntent(id: OrderId, paymentIntentId: string): Promise<Order | null>;
    updateCartItemQuantity(cartItemId: CartItemId, quantity: bigint): Promise<Cart | null>;
    updateOrderStatus(id: OrderId, status: OrderStatus): Promise<Order | null>;
    updateProduct(id: ProductId, req: UpdateProductRequest): Promise<Product | null>;
    updateStock(id: ProductId, newStock: bigint): Promise<Product | null>;
}
import type { AddToCartRequest as _AddToCartRequest, Cart as _Cart, CartItem as _CartItem, CartItemId as _CartItemId, CreateOrderRequest as _CreateOrderRequest, CreateProductRequest as _CreateProductRequest, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderItemRequest as _OrderItemRequest, OrderStatus as _OrderStatus, Product as _Product, ProductColor as _ProductColor, ProductId as _ProductId, ProductSize as _ProductSize, ProductTier as _ProductTier, Timestamp as _Timestamp, UpdateProductRequest as _UpdateProductRequest, UserId as _UserId, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addToCart(arg0: AddToCartRequest): Promise<Cart | null> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(to_candid_AddToCartRequest_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(to_candid_AddToCartRequest_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearMyCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearMyCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearMyCart();
            return result;
        }
    }
    async createOrder(arg0: CreateOrderRequest): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_CreateOrderRequest_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_CreateOrderRequest_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: CreateProductRequest): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(to_candid_CreateProductRequest_n26(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(to_candid_CreateProductRequest_n26(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyCart(): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyCart();
                return from_candid_Cart_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyCart();
            return from_candid_Cart_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrders();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrders();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrder(arg0);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrder(arg0);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllOrders();
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllOrders();
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listOrdersByStatus(arg0: OrderStatus): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrdersByStatus(to_candid_OrderStatus_n36(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrdersByStatus(to_candid_OrderStatus_n36(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProductsByTier(arg0: ProductTier): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductsByTier(to_candid_ProductTier_n28(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductsByTier(to_candid_ProductTier_n28(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeFromCart(arg0: CartItemId): Promise<Cart> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return from_candid_Cart_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return from_candid_Cart_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchProducts(arg0: string): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(arg0);
                return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(arg0);
            return from_candid_vec_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async setOrderPaymentIntent(arg0: OrderId, arg1: string): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.setOrderPaymentIntent(arg0, arg1);
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setOrderPaymentIntent(arg0, arg1);
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCartItemQuantity(arg0: CartItemId, arg1: bigint): Promise<Cart | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItemQuantity(arg0, arg1);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItemQuantity(arg0, arg1);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n36(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n36(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: ProductId, arg1: UpdateProductRequest): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, to_candid_UpdateProductRequest_n39(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, to_candid_UpdateProductRequest_n39(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateStock(arg0: ProductId, arg1: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateStock(arg0, arg1);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateStock(arg0, arg1);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_CartItem_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Cart_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cart): Cart {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_OrderItem_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderItem): OrderItem {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ProductTier_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductTier): ProductTier {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cart]): Cart | null {
    return value.length === 0 ? null : from_candid_Cart_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    tax: bigint;
    status: _OrderStatus;
    total: bigint;
    userId: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    stripePaymentIntentId: [] | [string];
    items: Array<_OrderItem>;
    orderNumber: string;
    subtotal: bigint;
}): {
    id: OrderId;
    tax: bigint;
    status: OrderStatus;
    total: bigint;
    userId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    stripePaymentIntentId?: string;
    items: Array<OrderItem>;
    orderNumber: string;
    subtotal: bigint;
} {
    return {
        id: value.id,
        tax: value.tax,
        status: from_candid_OrderStatus_n21(_uploadFile, _downloadFile, value.status),
        total: value.total,
        userId: value.userId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        stripePaymentIntentId: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.stripePaymentIntentId)),
        items: from_candid_vec_n23(_uploadFile, _downloadFile, value.items),
        orderNumber: value.orderNumber,
        subtotal: value.subtotal
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color: [] | [string];
    size: [] | [string];
    productId: _ProductId;
    productName: string;
    productTier: _ProductTier;
    quantity: bigint;
    price: bigint;
}): {
    color?: string;
    size?: string;
    productId: ProductId;
    productName: string;
    productTier: ProductTier;
    quantity: bigint;
    price: bigint;
} {
    return {
        color: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.color)),
        size: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.size)),
        productId: value.productId,
        productName: value.productName,
        productTier: from_candid_ProductTier_n10(_uploadFile, _downloadFile, value.productTier),
        quantity: value.quantity,
        price: value.price
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    imageUrls: Array<string>;
    name: string;
    createdAt: _Timestamp;
    tier: _ProductTier;
    description: string;
    sizes: Array<_ProductSize>;
    updatedAt: _Timestamp;
    stock: bigint;
    colors: Array<_ProductColor>;
    price: bigint;
}): {
    id: ProductId;
    imageUrls: Array<string>;
    name: string;
    createdAt: Timestamp;
    tier: ProductTier;
    description: string;
    sizes: Array<ProductSize>;
    updatedAt: Timestamp;
    stock: bigint;
    colors: Array<ProductColor>;
    price: bigint;
} {
    return {
        id: value.id,
        imageUrls: value.imageUrls,
        name: value.name,
        createdAt: value.createdAt,
        tier: from_candid_ProductTier_n10(_uploadFile, _downloadFile, value.tier),
        description: value.description,
        sizes: value.sizes,
        updatedAt: value.updatedAt,
        stock: value.stock,
        colors: value.colors,
        price: value.price
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tax: bigint;
    total: bigint;
    userId: _UserId;
    items: Array<_CartItem>;
    subtotal: bigint;
}): {
    tax: bigint;
    total: bigint;
    userId: UserId;
    items: Array<CartItem>;
    subtotal: bigint;
} {
    return {
        tax: value.tax,
        total: value.total,
        userId: value.userId,
        items: from_candid_vec_n6(_uploadFile, _downloadFile, value.items),
        subtotal: value.subtotal
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CartItemId;
    color: [] | [string];
    size: [] | [string];
    productId: _ProductId;
    productName: string;
    productTier: _ProductTier;
    imageUrl: [] | [string];
    addedAt: _Timestamp;
    quantity: bigint;
    price: bigint;
}): {
    id: CartItemId;
    color?: string;
    size?: string;
    productId: ProductId;
    productName: string;
    productTier: ProductTier;
    imageUrl?: string;
    addedAt: Timestamp;
    quantity: bigint;
    price: bigint;
} {
    return {
        id: value.id,
        color: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.color)),
        size: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.size)),
        productId: value.productId,
        productName: value.productName,
        productTier: from_candid_ProductTier_n10(_uploadFile, _downloadFile, value.productTier),
        imageUrl: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.imageUrl)),
        addedAt: value.addedAt,
        quantity: value.quantity,
        price: value.price
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    premium: null;
} | {
    average: null;
} | {
    basic: null;
}): ProductTier {
    return "premium" in value ? ProductTier.premium : "average" in value ? ProductTier.average : "basic" in value ? ProductTier.basic : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} | {
    completed: null;
} | {
    processing: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "paid" in value ? OrderStatus.paid : "completed" in value ? OrderStatus.completed : "processing" in value ? OrderStatus.processing : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_OrderItem>): Array<OrderItem> {
    return value.map((x)=>from_candid_OrderItem_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n7(_uploadFile, _downloadFile, x));
}
function to_candid_AddToCartRequest_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddToCartRequest): _AddToCartRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateOrderRequest_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateOrderRequest): _CreateOrderRequest {
    return to_candid_record_n15(_uploadFile, _downloadFile, value);
}
function to_candid_CreateProductRequest_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateProductRequest): _CreateProductRequest {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_OrderItemRequest_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderItemRequest): _OrderItemRequest {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_ProductTier_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductTier): _ProductTier {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateProductRequest_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateProductRequest): _UpdateProductRequest {
    return to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    items: Array<OrderItemRequest>;
}): {
    items: Array<_OrderItemRequest>;
} {
    return {
        items: to_candid_vec_n16(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    color?: string;
    size?: string;
    productId: ProductId;
    quantity: bigint;
}): {
    color: [] | [string];
    size: [] | [string];
    productId: _ProductId;
    quantity: bigint;
} {
    return {
        color: value.color ? candid_some(value.color) : candid_none(),
        size: value.size ? candid_some(value.size) : candid_none(),
        productId: value.productId,
        quantity: value.quantity
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageUrls: Array<string>;
    name: string;
    tier: ProductTier;
    description: string;
    sizes: Array<ProductSize>;
    stock: bigint;
    colors: Array<ProductColor>;
    price: bigint;
}): {
    imageUrls: Array<string>;
    name: string;
    tier: _ProductTier;
    description: string;
    sizes: Array<_ProductSize>;
    stock: bigint;
    colors: Array<_ProductColor>;
    price: bigint;
} {
    return {
        imageUrls: value.imageUrls,
        name: value.name,
        tier: to_candid_ProductTier_n28(_uploadFile, _downloadFile, value.tier),
        description: value.description,
        sizes: value.sizes,
        stock: value.stock,
        colors: value.colors,
        price: value.price
    };
}
function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    imageUrls?: Array<string>;
    name?: string;
    tier?: ProductTier;
    description?: string;
    sizes?: Array<ProductSize>;
    stock?: bigint;
    colors?: Array<ProductColor>;
    price?: bigint;
}): {
    imageUrls: [] | [Array<string>];
    name: [] | [string];
    tier: [] | [_ProductTier];
    description: [] | [string];
    sizes: [] | [Array<_ProductSize>];
    stock: [] | [bigint];
    colors: [] | [Array<_ProductColor>];
    price: [] | [bigint];
} {
    return {
        imageUrls: value.imageUrls ? candid_some(value.imageUrls) : candid_none(),
        name: value.name ? candid_some(value.name) : candid_none(),
        tier: value.tier ? candid_some(to_candid_ProductTier_n28(_uploadFile, _downloadFile, value.tier)) : candid_none(),
        description: value.description ? candid_some(value.description) : candid_none(),
        sizes: value.sizes ? candid_some(value.sizes) : candid_none(),
        stock: value.stock ? candid_some(value.stock) : candid_none(),
        colors: value.colors ? candid_some(value.colors) : candid_none(),
        price: value.price ? candid_some(value.price) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductTier): {
    premium: null;
} | {
    average: null;
} | {
    basic: null;
} {
    return value == ProductTier.premium ? {
        premium: null
    } : value == ProductTier.average ? {
        average: null
    } : value == ProductTier.basic ? {
        basic: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    paid: null;
} | {
    completed: null;
} | {
    processing: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.cancelled ? {
        cancelled: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.paid ? {
        paid: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.processing ? {
        processing: null
    } : value;
}
function to_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<OrderItemRequest>): Array<_OrderItemRequest> {
    return value.map((x)=>to_candid_OrderItemRequest_n17(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
